# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"render",
	"math",
	"viewer",
	"importer",
	"k-nearest",
	"common",
	"input",
]
resolver = "2"
