[package]
name = "render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math.workspace = true
input.workspace = true
bytemuck.workspace = true
env_logger.workspace = true
image.workspace = true
log.workspace = true
wgpu.workspace = true
winit.workspace = true
wgpu_text.workspace = true
