[package]
name = "importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render.workspace = true
math.workspace = true
k-nearest.workspace = true
common.workspace = true
rand.workspace = true
serde.workspace = true
num_cpus.workspace = true
crossbeam.workspace = true
las.workspace = true
