[package]
name = "ui"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math.workspace = true
render.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
